swagger: '2.0'
info:
  title: TopBlogger REST API
  description: |
    REST API for TopBlogger.
  version: "0.0.0"
# the domain of the service
# TODO to be updated for final deployment
host: sample.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /api
security:
  - topBloggerAuth:
      - read
      - write_blog
      - write_comment
securityDefinitions:
  topBloggerAuth:
    type: oauth2
    description: The OAuth 2 security scheme used by the TopBlogger APIs
    flow: accessCode
    authorizationUrl: https://security.example.com/ar/api/auth/authorize #TODO to be updated in final deployment
    tokenUrl: https://security.example.com/ar/api/auth/token             #TODO to be updated in final deployment
    scopes:   #TODO to be updated in final deployment
      read: scope to read all the user-related information
      write_blog: scope to write the user-related blogs
      write_comment: scope to write the user-related comments

paths:
  /blogs:
    post:
      summary: Create a Blog
      description: |
        This method will create a blog.
      tags:
        - Blog
      security:
        - topBloggerAuth:
          - write_blog
    get:
      summary: List Blogs
      description: |
        This method returns the blogs that matches filter.
      tags:
        - Blog
      security:
        - topBloggerAuth:
          - read
  /blogs/{id}:
    put:
      summary: Update a Blog.
      description: |
        This method will update a blog. It can only be done by the author of blog.
      tags:
        - Blog
      security:
        - topBloggerAuth:
          - write_blog
    get:
      summary: Get a Blog by ID.
      description: |
        This method will get a blog by ID.
      tags:
        - Blog
      security:
        - topBloggerAuth:
          - read
    delete:
      summary: Delete a Blog by ID.
      description: |
        This method will delete a blog by ID. It can only be done by the author of blog. Both of published or unpublished blogs can be deleted.
      tags:
        - Blog
      security:
        - topBloggerAuth:
          - write_blog
  /blogs/{id}/publish:
    post:
      summary: Publish a Blog
      description: |
        This method will publish a unpublished blog. It can only be done by the author of blog.
      tags:
        - Blog
      security:
        - topBloggerAuth:
          - write_blog
  /blogs/{id}/view:
    post:
      summary: Mark a Blog as Viewed
      description: |
        This method will mark a blog as viewed by current user. A blog can be marked as viewed by the same user for at most once. The current user should not be the author of blog.
      tags:
        - Blog
      security:
        - topBloggerAuth:
          - write_blog
  /blogs/{id}/upvote:
    post:
      summary: Up-Vote a Blog
      description: |
        This method will up-vote a blog by current user. A blog can be up-voted by the same user for at most once. The author of blog cannot vote for the his/her blog.
      tags:
        - Blog
      security:
        - topBloggerAuth:
          - write_blog
  /blogs/{id}/votes/downvote:
    post:
      summary: Down-Vote a Blog
      description: |
        This method will down-vote a blog by current user. A blog can be up-voted by the same user for at most once. The author of blog cannot vote for the his/her blog.
      tags:
        - Blog
      security:
        - topBloggerAuth:
          - write_blog
  /blogs/{id}/comments:
    post:
      summary: Add a Comment
      description: |
        This method will add a comment for the blog.
      tags:
        - Blog
        - Comment
      security:
        - topBloggerAuth:
          - write_comment
  /blogs/{blogId}/comments/{commentId}:
    put:
      summary: Update a Comment
      description: |
        This method will update a comment. It can only be done by the author of comment.
      tags:
        - Blog
        - Comment
      security:
        - topBloggerAuth:
          - write_comment
    delete:
      summary: Delete a Comment
      description: |
        This method will delete a comment. It can only be done by the author of comment, or the author of blog.
      tags:
        - Blog
        - Comment
      security:
        - topBloggerAuth:
          - write_comment
  /blogs/{blogId}/comments/{commentId}/like:
    post:
      summary: Like a Comment
      description: |
        This method will make a comment as liked by current user. The author of comment cannot mark the his/her comment as liked.
      tags:
        - Blog
        - Comment
      security:
        - topBloggerAuth:
          - write_comment
  /blogs/{blogId}/comments/{commentId}/dislike:
    post:
      summary: Dislike a Comment
      description: |
        This method will make a comment as disliked by current user. The author of comment cannot mark the his/her comment as disliked.
      tags:
        - Blog
        - Comment
      security:
        - topBloggerAuth:
          - write_comment